CREATE TABLE IF NOT EXISTS chat_session (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id BIGINT NULL,
    product_id BIGINT NULL,
    context_type VARCHAR(32) NULL,
    session_status TINYINT NOT NULL DEFAULT 1,
    message_count INT NOT NULL DEFAULT 0,
    last_question VARCHAR(500) NULL,
    last_answer_summary VARCHAR(500) NULL,
    created_at DATETIME NOT NULL,
    last_active_at DATETIME NOT NULL,
    expire_at DATETIME NOT NULL,
    UNIQUE KEY uk_chat_session_session_id (session_id),
    KEY idx_chat_session_user_last_active (user_id, last_active_at),
    KEY idx_chat_session_product_last_active (product_id, last_active_at),
    KEY idx_chat_session_expire_at (expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_record (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id BIGINT NULL,
    product_id BIGINT NULL,
    record_no INT NOT NULL,
    question VARCHAR(500) NOT NULL,
    question_category VARCHAR(32) NULL,
    answer TEXT NOT NULL,
    answer_policy VARCHAR(64) NOT NULL,
    sources_json LONGTEXT NULL,
    hit_knowledge_json LONGTEXT NULL,
    confidence DECIMAL(6,4) NULL,
    fallback_reason VARCHAR(64) NULL,
    audit_summary VARCHAR(1000) NULL,
    model_name VARCHAR(64) NULL,
    latency_ms INT NULL,
    estimated_tokens INT NULL,
    created_at DATETIME NOT NULL,
    expire_at DATETIME NOT NULL,
    KEY idx_chat_record_session_record_no (session_id, record_no),
    KEY idx_chat_record_session_created_at (session_id, created_at),
    KEY idx_chat_record_product_created_at (product_id, created_at),
    KEY idx_chat_record_user_created_at (user_id, created_at),
    KEY idx_chat_record_expire_at (expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
