spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.100.130:8848
      discovery:
        namespace: cac2e129-5c78-402a-bdd1-b9dbb0892486
        # 确保 Nacos 客户端完全初始化后再注册
        register-enabled: true
      config:
        enabled: false
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: seckill-service
          uri: lb://seckill-service
          predicates:
            - Path=/seckill/**
        - id: seckill-product-service
          uri: lb://seckill-service
          predicates:
            - Path=/seckill-product/**
        - id: product-service
          uri: lb://seckill-service
          predicates:
            - Path=/product/**
server:
  port: 8080
flash-sale:
  jwt:
    location: classpath:flash-sale.jks
    alias: flash-sale
    password: 123321
    tokenTTL: 30m
  auth:
    excludePaths:
      - /auth/login
      - /auth/register
