spring.application.name=seckill-service
server.port=8081
spring.data.redis.host=192.168.100.130
spring.data.redis.port=6379
spring.data.redis.password=123321
spring.rabbitmq.host=192.168.100.130
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

