spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/flash_sale?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.100.130
      port: 6379
      password: 123321
  rabbitmq:
    host: 192.168.100.130
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      server-addr: 192.168.100.130:8848
      discovery:
        namespace: cac2e129-5c78-402a-bdd1-b9dbb0892486
        # 确保 Nacos 客户端完全初始化后再注册
        register-enabled: true
      config:
        enabled: false

server:
  port: 8082

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.flashsale.orderservice.domain.po,com.flashsale.orderservice.domain.vo
  configuration:
    map-underscore-to-camel-case: true
