server:
  port: 8083
  forward-headers-strategy: framework
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/flash_sale?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 192.168.100.130:8848
      discovery:
        namespace: cac2e129-5c78-402a-bdd1-b9dbb0892486
        # 服务注册延迟，确保 Nacos 客户端完全初始化
        register-enabled: true
      config:
        enabled: false




flash-sale:
  jwt:
    location: classpath:flash-sale.jks
    alias: flash-sale
    password: 123321
    tokenTTL: 30m
