spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - optional:nacos:flash-sale-common.yaml?group=${FLASH_SALE_NACOS_GROUP:FLASH_SALE}
      - optional:nacos:flash-sale-mysql.yaml?group=${FLASH_SALE_NACOS_GROUP:FLASH_SALE}
      - optional:nacos:flash-sale-redis.yaml?group=${FLASH_SALE_NACOS_GROUP:FLASH_SALE}
      - optional:nacos:flash-sale-jwt.yaml?group=${FLASH_SALE_NACOS_GROUP:FLASH_SALE}
      - optional:nacos:${spring.application.name}.yaml?group=${FLASH_SALE_NACOS_GROUP:FLASH_SALE}
  cloud:
    nacos:
      server-addr: ${FLASH_SALE_NACOS_ADDR:192.168.100.130:8848}
      discovery:
        namespace: ${FLASH_SALE_NACOS_NAMESPACE:cac2e129-5c78-402a-bdd1-b9dbb0892486}
        register-enabled: true
      config:
        enabled: ${FLASH_SALE_NACOS_CONFIG_ENABLED:true}
        namespace: ${FLASH_SALE_NACOS_NAMESPACE:cac2e129-5c78-402a-bdd1-b9dbb0892486}
        group: ${FLASH_SALE_NACOS_GROUP:FLASH_SALE}
        file-extension: yaml
        refresh-enabled: true

server:
  port: ${FLASH_SALE_AUTH_PORT:8083}
